name: Shipping CI Pipeline
run-name: Shipping CI Pipeline
on: [push, workflow_dispatch]

jobs:
  lint:
    runs-on: self-hosted
    steps:
      - run: echo "mvn checkstyle:check"

  test:
    needs: build
    runs-on: self-hosted
    steps:
      - run: echo "Test Cases"

  ci:
    needs: test
    uses: raghudevopsb89/github-actions/.github/workflows/ci.yml@main
    with:
      component_name: shipping
